# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Game
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.1

# Loader
enabled_platforms = fabric,forge
fabric_loader_version=0.19.5
fabric_api_version=0.92.12+1.20.1
forge_version=1.20.1-47.4.22

# Mod
maven_group=net.spell_power
archives_name=spell_power
mod_version=1.6.0.005
minecraft_compat_version=1.20.1

# Dependencies
tiny_config_version=3.1.0+1.20.1
