modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "spell_power"
version = "${version}"
displayName = "Spell Power Attribute"
authors = "Daedelus"
description = '''
Spell Power entity attributes with related status effects and enchantments.
'''
logoFile = "assets/spell_power/icon.png"

[[dependencies.spell_power]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_power]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

# Forgified Fabric API
[[dependencies.spell_power]]
modId = "fabric_api_base"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "spell_power.mixins.json"
